// <auto-generated />
namespace SuperApp.Backoffice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApiKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApiKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201809161217176_ApiKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
